---
product_title: Kings Landing
product_description: Growing up at Winterfell, all I ever wanted was to escape, to
  come here, to the capital. To see the southern knights and their painted armor,
  and King's Landing after dark. All the candles burning in all those windows.
subscribe_headline: Be the first to know when KingsLanding is live and ready for you.
seo_title: Kings Landing - The great city of GOT
seo_keywords: city, game of thrones, kings landing, war, series, tv show
seo_description: King's Landing is the capital, and largest city, of the Seven Kingdoms.
subscribe_button_color: "#935942"
subscribe_button_text: Subscribe
background_image_url: https://c2.staticflickr.com/8/7287/27854985275_978e3f2163_b.jpg
google_drive_credentials: 510843062291-nsmn6rrgort373ofpptll267brp3r88b.apps.googleusercontent.com:D9aQkrSCn8XWpkfceXYlnWQ-:1/ILu995DuxQHqCfkhxfGnvkqzGxwqHp1vbNNTeSAb9ho
spreadsheet_key: 1Uepgo8_MyxqQrpr-ON94Q26Pyi0I9zTvno19kecef4I
google_analytics_key: ''
